### ISSUE TITLE
Todo: 3 features on my wishlist

### ISSUE THREAD

**Issue by ghost** [natcl/maxtoolbox#2]
clear message window
(appears to be some hacking on maxinterface.json)
(can be done indirectly via Cmd +` then Cmd+a then  Del)

grab multiple boxes 
(as in one is already grabbed, use perhaps shift+cmd +d-key to select nearby box)

autoalign/route
Perhaps this is around and I haven't found it. 

I'm not opposed to hacking these together. Just thought this the proper place to post about it. Sorry if this isn't useful.

**Comment by tmhglnd** [comment]
I added `shift-b` to send bangs to selected objects: 5b4297da24061f500f4c6dcaf0bdc3ccd429fe73

**Comment by natcl** [comment]
Thanks ! Closing this then.
